# Generated by Django 3.0.2 on 2020-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Cance',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.EmailField(help_text='email adress', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Icon',
            field=models.CharField(help_text='Enter field documentation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Pass',
            field=models.CharField(help_text='Pass word', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Rang',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='User_Gun',
            field=models.TextField(help_text='Enter gun piy piy', null=True),
        ),
    ]
