# Generated by Django 3.0.2 on 2020-05-15 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0002_auto_20200512_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Icon', models.CharField(help_text='Enter field documentation', max_length=100, null=True)),
                ('Rang', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('Cance', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('User_Gun', models.TextField(help_text='Enter gun piy piy', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
